language: ruby
rvm:
  - 2.1.1
script: "rake default"
branches:
  only:
    - master
env:
  - PUPPET_VERSION=3.7.4
  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.5.1
  - PUPPET_VERSION=3.4.3
  - PUPPET_VERSION=3.3.2
  - PUPPET_VERSION=3.2.4
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=2.7.24
  - PUPPET_VERSION=2.6.18
notifications:
  email: github@dimitri.eu
gemfile: Gemfile
